# Generated by Django 5.2.8 on 2025-11-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie'), ('documental', 'Documental')], max_length=20)),
                ('fecha_lanzamiento', models.DateField()),
                ('categoria', models.IntegerField()),
                ('capitulos', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calidad_video', models.CharField(max_length=20)),
                ('num_dispositivos', models.IntegerField()),
                ('beneficio_extra', models.TextField()),
                ('descarga_offline', models.BooleanField(default=False)),
                ('contenidos_exclusivos', models.ManyToManyField(blank=True, related_name='suscripciones_exclusivas', to='app_Crunchyroll.contenido')),
            ],
            options={
                'db_table': 'suscripcion',
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_principales', to='app_Crunchyroll.suscripcion'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_principales', to='app_Crunchyroll.suscripcion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='usuarios_premium',
            field=models.ManyToManyField(blank=True, related_name='suscripciones_adicionales', to='app_Crunchyroll.usuario'),
        ),
    ]
